// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mvhvystijtjtpeeziqgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im12aHZ5c3RpanRqdHBlZXppcWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzQ1OTksImV4cCI6MjA1ODE1MDU5OX0.R1rATN-qx91Oeo-hmVmU85-7nwxdERcuik5FE3m_cUE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);